name: Llmsr-Llama31_8b
class_name: LLMSRSearcher
api_type: hfinf
api_model: meta-llama/Llama-3.1-8B-Instruct
api_url: https://api-inference.huggingface.co/models/meta-llama/Meta-Llama-3-8B
global_max_sample_num: 1000
samples_per_prompt: 4
num_islands: 10