name: Llmsr-Llama31_8b-SurfaceBench
class_name: methods.llmsr.searcher.LLMSRSearcher
api_type: hfinf
api_model: meta-llama/Llama-3.1-8B-Instruct
api_url: https://api-inference.huggingface.co/models/meta-llama/Meta-Llama-3-8B-Instruct
global_max_sample_num: 2000
samples_per_prompt: 4
num_islands: 10
evaluate_timeout_seconds: 300
functions_per_prompt: 1
num_samplers: 4
num_evaluators: 4